[default]
# Sep 2026
options.token_file_path = ~/.config/openrouter.token
options.endpoint_url = https://openrouter.ai/api/v1/chat/completions
options.reasoning = {"enabled": true, "effort": "high"}
options.model = openai/gpt-6.1-sol

[claude]
# Sep 2026
options.model = anthropic/claude-opus-5.5

[gpt]
# Sep 2026
options.model = openai/gpt-6-astra
