scriptencoding utf-8

" All available fonts: 'set guifont=*'
let &guifont = 'DejaVu Sans Mono 11.5'
" GUI version of clipboard=unnamedplus
set guioptions-=a
set guioptions+=P
" Use console dialogs
set guioptions+=c
" Disable menubar
set guioptions-=m
" Disable tearoff menus
set guioptions-=t
" Disable toolbar
set guioptions-=T
" Disable scrollbars
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
set guioptions-=h
